language: java
sudo: true
before_install:
  - mvn clean && mvn -N io.takari:maven:0.7.6:wrapper && chmod +x mvnw
stages:
  - compile
  - test
jobs:
  include:
    - stage: compile
      script: mvn compile
    - stage: test
      script: mvn test
deploy:
  provider: heroku
  api_key: 4788febb-d90c-45f5-84c3-d31d91a7f423
  app:
    master: organiser-app
    cd: organiser-app-dev
