language: java
sudo: true
before_install:
  - mvn clean && mvn -N io.takari:maven:0.7.6:wrapper && chmod +x mvnw
stages:
  - compile
  - test
  - name: deploy
    # require the branch name to be master
    # if: branch = master
jobs:
  include:
    - stage: compile
      script: mvn compile
    - stage: test
      script: mvn test
    - stage: deploy
      script: skip # to be added
deploy:
  provider: heroku
  app: organiser-app
  api_key:
    secure: 750485f6-8805-4575-a7d2-1be7b8c601b7
