language: java

stages:
  - test
  - build
  - name: deploy
    # require the branch name to be master
    if: branch = master
jobs:
  include:
    - stage: test
      script: skip # to be added
    - stage: build
      script: skip # to be added
    - stage: deploy
      script: skip # to be added