language: java

stages:
  - compile
  - test
  - name: deploy
    # require the branch name to be master
    if: branch = master
jobs:
  include:
    - stage: compile
      script: cd StudentGroupingOrganiser/ && mvn compile
    - stage: test
      script: cd StudentGroupingOrganiser/ && mvn test
    - stage: deploy
      script: skip # to be added